---
title: "Running code from *Empirical Research in Accounting: Tools and Methods*"
format: gfm
wrap: none
bibliography: book.bib
---

To get going with [*Empirical Research in Accounting: Tools and Methods*](https://iangow.github.io/far_book/), follow these steps:

1. Complete steps 1--3 from [here](https://iangow.github.io/far_book/intro.html#sec-install).
(Step 4 is unnecessary for the parquet-based setup we're using here.)

2. Download the RStudio project from [here](https://github.com/iangow/far_example).
One way to download it is to click the green "Code" button then "Download ZIP" and then unzip the downloaded file.

3. Run the code in the Python notebook [here](https://github.com/iangow/far_templates/blob/main/get_wrds_data.ipynb), but after setting `DATA_DIR` to the `data` directory inside the project folder you created in the Step 2.
(If you had already run the Python notebook, just move your existing `data` directory into the project folder you created in Step 2.
Alternatively, just edit the `.Renviron` file in the project directory so that `DATA_DIR` refers to the location of the data directory on your computer and reopen the project in RStudio.)

4. Open the RStudio project you downloaded in Step 2, and then open the file `bb68-pq.qmd` inside RStudio.

5. With `bb68-pq.qmd` open in RStudio, click the "Render" button.
This will take a little time, but at the end you will have a rendered replication of @Ball:1968ub as seen [here](https://iangow.github.io/far_book/bb68.html#replicating-ball1968ub).
(I have also included `bb68-pq-pdf.qmd`, which renders directly to a PDF, but may require additional setup.
Note that it's not necessary to have two files like this; as discussed [here](https://quarto.org/docs/get-started/authoring/rstudio.html), it's possible to have a single file that can be rendered into either format.)

6. To work on another chapter of [*Empirical Research in Accounting: Tools and Methods*](https://iangow.github.io/far_book/), you can download the associated "Parquet template" from [here](https://github.com/iangow/far_templates/blob/main/README.md) by right-clicking and downloading the linked file to the project directory you created in Step 2.

## References {-}
